### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by ruolin** [mikelove/fragmentBiasSimulation#1]
for the line load("data/geuvadisFPKM.rda") in simulate_make_data.R
the file is not generated.

**Comment by mikelove** [comment]
hi,

I've added some R data objects for running these R scripts.

Note that, the code in this repo uses an old Polyester fork (hosted on github) that I had created while we were submitting the manuscript. This fork is now unnecessary, because after the manuscript was accepted, I incorporated code for running a Polyester simulation with alpine's fragment GC bias curves into the "official" Polyester repo hosted on Bioconductor.

So it is now cleaner to use the official Polyester interface, and there is code in the alpine vignette (on Bioconductor) for how to pass alpine's estimated fragment GC bias curves to Polyester for simulation.

This repo is for documenting the code from the manuscript as is, and so I didn't change it.
